#!/bin/bash
cd einventory-service 
./Makefile
docker build -t einventory .
cd ../epayment-service
./Makefile
docker build -t epayment .
cd ../etransaction-service
./Makefile
docker build -t etransaction .