#!/bin/bash
mvn clean install -DskipTests
cd einventory-service 
./Makefile
docker build -t einventory .
cd ../epayment-service
./Makefile
docker build -t epayment .
cd ../etransaction-service
./Makefile
docker build -t etransaction .
cd ../transaction-historical
./Makefile
docker build -t transactionview .